algoritmo "Converão de temperaturas"
// Função : Converter Fahrenheit para Celsius
// Autor : Alfredo Henrique Grun
// Data : 10/11/2022
// Seção de Declarações 

var
tempFahrenheit, tempCelsius: real


inicio
Escreval("Digite a temperatura em graus ºF (Fahrenheit)")
leia(tempFahrenheit)

tempCelsius <- (tempFahrenheit - 32)/1.8

Escreval("A temperatura em graus ºC (Celsius) é:", tempCelsius)



fimalgoritmo
